### ISSUE TITLE
error occurred after image file have been uploaded

### ISSUE THREAD

**Issue by daffatahtaa** [Nix4444/Pimeyes-scraper#1]
DevTools listening on ws://127.0.0.1:62473/devtools/browser/e2d20089-1a76-4667-9f6b-2a30ab42a743
An exception occurred: Message:
Stacktrace:
        GetHandleVerifier [0x00007FF6CEC9AD22+56930]
        (No symbol) [0x00007FF6CEC0F622]
        (No symbol) [0x00007FF6CEAC42E5]
        (No symbol) [0x00007FF6CEB098ED]
        (No symbol) [0x00007FF6CEB09A2C]
        (No symbol) [0x00007FF6CEB4A967]
        (No symbol) [0x00007FF6CEB2BCDF]
        (No symbol) [0x00007FF6CEB481E2]
        (No symbol) [0x00007FF6CEB2BA43]
        (No symbol) [0x00007FF6CEAFD438]
        (No symbol) [0x00007FF6CEAFE4D1]
        GetHandleVerifier [0x00007FF6CF016AAD+3709933]
        GetHandleVerifier [0x00007FF6CF06FFED+4075821]
        GetHandleVerifier [0x00007FF6CF06817F+4043455]
        GetHandleVerifier [0x00007FF6CED39756+706710]
        (No symbol) [0x00007FF6CEC1B8FF]
        (No symbol) [0x00007FF6CEC16AE4]
        (No symbol) [0x00007FF6CEC16C3C]
        (No symbol) [0x00007FF6CEC068F4]
        BaseThreadInitThunk [0x00007FF8B237257D+29]
        RtlUserThreadStart [0x00007FF8B3B6AA58+40]

Results:  None
URL:  None

**Comment by TheFrenchPepeAI** [comment]
same

**Comment by Koalamanx** [comment]
So this doesnt work anymore?

**Comment by Nix4444** [comment]
No, it does work.
